#!/bin/bash

# virtualenv --system-site-packages ansible-env
# Workaround the following is executed in script 
# in current shell instead of forking

export ANSIBLE_LIBRARY=~/pristimantis/modules

#. ./ansible-env/bin/activate
#pip install ansible
source ~stack/stackrc
echo "############# COPY THE FOLLOWING TO YOUR /etc/hosts FILE #############"
bash scripts/openstack/prepare-etc-hosts.sh
