---
- name: Validate stonith devices
  hosts: Controller
  user: heat-admin
  vars:
    metadata:
      name: get_stonith.yml
      description: >
        Verify that stonith devices are configured for your OpenStack Platform HA cluster
  become: true
  tasks:
  - name: Check if we are in HA cluster environment
    register: pcs_cluster_status
    command: pcs cluster status
    failed_when: false
    changed_when: false

  - name: Get all currently configured stonith devices
    when: "pcs_cluster_status.rc == 0"
    register: stonith_devices
    command: "pcs stonith"
    changed_when: false

  - name: Verify the stonith device are configured
    fail:
      msg: "Stonith devices are not configured."
    when: >
      pcs_cluster_status.rc == 0
      and
      'NO stonith devices configured' in stonith_devices.stdout
